### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Bogdis** [iRayanKhan/homebridge-tuya-platform#3]
Hi,

How do i install this one?

Best regards.

**Comment by iRayanKhan** [comment]
Hi @Bogdis, currently you have to navigate to your plugin folder then do:
``` git clone https://github.com/iRayanKhan/homebridge-tuya-lan```
I will publish this plugin to NPM tonight after doing a final test.

**Comment by Bogdis** [comment]
Ok, thank you.

**Comment by Bogdis** [comment]
Hi, just install this but cant get in to work just like the other plugin. :(
Tried Tuya, Smart Life and Ucomen
Getting:
Error: EPIPE { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }

and

Error: undefined Error: This socket is closed
    at Socket._writeGeneric (net.js:733:18)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
Error: undefined Error: TLS handshake timeout
    at TLSSocket._handleTimeout (_tls_wrap.js:596:22)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by Bogdis** [comment]
Hi, 
Got it to work thank you so mutch:)

**Comment by Bogdis** [comment]
Hi again,

Ive gott everything working but i think that i have a problem or 2 do you think you can help me?

First when i restart homebridge my devices show up as off in homekit app and when i click the device nothing happens it just turns to on position, after that it works great.

The second thing is i get [TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
al the time it just scrolling through with different ip number. Is this normal?

Thanks

**Comment by iRayanKhan** [comment]
Hi @Bogdis Do you mind pasting the full log? Also what made the first part starting working just incase other people have this issue.

**Comment by Bogdis** [comment]
> Hi @Bogdis Do you mind pasting the full log? Also what made the first part starting working just incase other people have this issue.

Hi i didint do anything special just changed homebridge port and started over again with the process and it worked.

Here is my log:

Started Node.js HomeKit Server.
[2020-1-30 08:25:14] Loaded config.json with 6 accessories and 6 platforms.
[2020-1-30 08:25:15] ---
[2020-1-30 08:25:15] Loaded plugin: homebridge-config-ui-x
[2020-1-30 08:25:15] Registering platform 'homebridge-config-ui-x.config'
[2020-1-30 08:25:15] ---
[2020-1-30 08:25:15] Loaded plugin: homebridge-dummy
[2020-1-30 08:25:15] Registering accessory 'homebridge-dummy.DummySwitch'
[2020-1-30 08:25:15] ---
[2020-1-30 08:25:17] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[2020-1-30 08:25:17] Registering platform 'homebridge-eWeLink.eWeLink'
[2020-1-30 08:25:17] ---
[2020-1-30 08:25:19] Loaded plugin: homebridge-harmonyhub-plugin
[2020-1-30 08:25:19] Registering platform 'homebridge-harmonyhub-plugin.HarmonyHub'
[2020-1-30 08:25:19] ---
[2020-1-30 08:25:19] Plugin /usr/lib/node_modules/homebridge-hue requires Node version of ^12.14.1 which does not satisfy the current Node version of v8.17.0. You may need to upgrade your installation of Node.
[2020-1-30 08:25:28] Loaded plugin: homebridge-hue
[2020-1-30 08:25:28] Registering platform 'homebridge-hue.Hue'
[2020-1-30 08:25:28] ---
[2020-1-30 08:25:28] Loaded plugin: homebridge-magichome2
homebridge API version: 2.4
[2020-1-30 08:25:28] Registering accessory 'homebridge-magichome.MagicHome'
[2020-1-30 08:25:28] ---
[2020-1-30 08:25:30] Loaded plugin: homebridge-plex-v2
[2020-1-30 08:25:30] Registering accessory 'homebridge-plex.Plex'
[2020-1-30 08:25:30] ---
[2020-1-30 08:25:31] Loaded plugin: homebridge-tplink-smarthome
[2020-1-30 08:25:31] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[2020-1-30 08:25:31] ---
[2020-1-30 08:25:31] Loaded plugin: homebridge-tuya-lan2
[2020-1-30 08:25:31] Registering platform 'homebridge-tuya-lan.TuyaLan'
[2020-1-30 08:25:31] ---
[2020-1-30 08:25:31] Loading 6 platforms...
[2020-1-30 08:25:31] [Homebridge Ui] Initializing config platform...
[2020-1-30 08:25:31] [Homebridge Ui] Spawning homebridge-config-ui-x with PID 867
[2020-1-30 08:25:31] [eWeLink] Initializing eWeLink platform...
[2020-1-30 08:25:31] [eWeLink] Intialising eWeLink
[2020-1-30 08:25:31] [eWeLink] Found 0 group(s)
[2020-1-30 08:25:31] [Hue] Initializing Hue platform...
[2020-1-30 08:25:31] [Hue] homebridge-hue v0.11.51, node v8.17.0, homebridge v0.4.50
[2020-1-30 08:25:31] [Hue] warning: not using recommended node version v12.14.1 LTS
[2020-1-30 08:25:31] [homebridge-harmonyhub-plugin] Initializing HarmonyHub platform...
[2020-1-30 08:25:31] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[2020-1-30 08:25:31] [TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v8.17.0, homebridge v0.4.50
[2020-1-30 08:25:31] [TuyaLan] Initializing TuyaLan platform...
[2020-1-30 08:25:31] Loading 6 accessories...
[2020-1-30 08:25:31] [Plex] Initializing Plex accessory...
[2020-1-30 08:25:31] [Bio] Initializing Plex accessory...
[2020-1-30 08:25:31] [Oscars Säng Lampa] Initializing MagicHome accessory...
[2020-1-30 08:25:31] [Devas Säng Lampa] Initializing MagicHome accessory...
[2020-1-30 08:25:31] [Switch 1] Initializing DummySwitch accessory...
[2020-1-30 08:25:32] [Switch 2] Initializing DummySwitch accessory...
[2020-1-30 08:25:32] [TplinkSmarthome] Configuring cached accessory: [Sänglampa]xxxxxxxxxxxxxxxxxxxxxxxxx
[2020-1-30 08:25:32] [TplinkSmarthome] Configuring cached accessory: [Garage] xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2020-1-30 08:25:32] [TuyaLan] Marked Fönsterlampa kök unreachable by faulting Service.Fönsterlampa kök.On
[2020-1-30 08:25:32] [TuyaLan] Marked Devas Fönsterlampa unreachable by faulting Service.Devas Fönsterlampa.On
[2020-1-30 08:25:32] [TuyaLan] Marked Smart Socket unreachable by faulting Service.Smart Socket.On
[2020-1-30 08:25:32] [TuyaLan] Marked Garage Port unreachable by faulting Service.Garage Port.Target Door State
[2020-1-30 08:25:32] [TuyaLan] Marked Fönsterlampa vardagsrum unreachable by faulting Service.Fönsterlampa vardagsrum.On
[2020-1-30 08:25:32] [TuyaLan] Marked Matlampa unreachable by faulting Service.Matlampa.On
[2020-1-30 08:25:32] [eWeLink] Garage Port Configure Accessory
[2020-1-30 08:25:32] [eWeLink] Bio lampa Configure Accessory
[2020-1-30 08:25:32] [eWeLink] Devas tak lampa Configure Accessory
[2020-1-30 08:25:32] [eWeLink] Kök lampa Configure Accessory
[2020-1-30 08:25:32] [eWeLink] A total of [4] accessories were loaded from the local cache
[2020-1-30 08:25:32] [eWeLink] Sending login request with user credentials: {"email":"myemail","password":"Xxxxxx","version":"6","ts":"xxxxxxxx","nonce":"xxxxxxxxxxx","appid":"xxxxxxxxxxxxxxx","imei":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","os":"iOS","model":"iPhone10,6","romVersion":"11.1.2","appVersion":"3.5.3"}
[2020-1-30 08:25:32] [eWeLink] Login signature: xxxxxxxxxxxxxxxxxxxxxx
[2020-1-30 08:25:32] [TuyaLan] Starting discovery...
[TuyaDiscovery] Discovery started on port 6666.
[TuyaDiscovery] Discovery started on port 6667.
[2020-1-30 08:25:32] [TplinkSmarthome] New Device Online: [Sänglampa] plug [xxxxxxxxxxxxxxxxxxx] 192.168.x.xx:xxxx
[2020-1-30 08:25:32] [TplinkSmarthome] Adding: [Sänglampa] plug [xxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:32] [TplinkSmarthome] New Device Online: [Garage] plug [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] ip adress
[2020-1-30 08:25:32] [TplinkSmarthome] Adding: [Garage] plug [xxxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:32] [Oscars Säng Lampa] DEVICE COLOR - (H,S,V): 209,100,100  (R,G,B): 0,132,255
[2020-1-30 08:25:32] [Devas Säng Lampa] DEVICE COLOR - (H,S,V): 67,82,76  (R,G,B): 176,194,35
[TuyaDiscovery] UDP from (ip adress) 0x000055aa...0x0000aa55
[2020-1-30 08:25:33] [TuyaLan] Discovered Matlampa (xxxxxxxxxxxxxx) identified as SimpleLight (3.3)
[TuyaAccessory] Changing ping gap for Matlampa to 9s
[2020-1-30 08:25:33] [TuyaLan] Connected to Matlampa
[TuyaAccessory] Sending first query to Matlampa (3.3)
[TuyaAccessory] Heard back from Matlampa with command 10
[2020-1-30 08:25:33] [TuyaLan] Ready to handle Matlampa (SimpleLight:3.3) with signature {"1":false,"2":false,"5":0}
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[2020-1-30 08:25:33] [TuyaLan] Discovered Garage Port (xxxxxxxxxxxxxxx) identified as GarageDoor (3.3)
[TuyaAccessory] Changing ping gap for Garage Port to 9s
[2020-1-30 08:25:33] [TuyaLan] Connected to Garage Port
[TuyaAccessory] Sending first query to Garage Port (3.3)
[TuyaAccessory] Heard back from Garage Port with command 10
[2020-1-30 08:25:33] [TuyaLan] Ready to handle Garage Port (GarageDoor:3.3) with signature {"1":false,"101":false}
[2020-1-30 08:25:43] [eWeLink] Authentication token received [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:43] [eWeLink] WebSocket host received [eu-pconnect4.coolkit.cc]
[2020-1-30 08:25:43] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-api.coolkit.cc:8080]
[2020-1-30 08:25:43] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
[2020-1-30 08:25:43] [homebridge-harmonyhub-plugin] {HarmonyHub} <xxxxxxxxxxxxxxxxxxxxxxxxxx> <Harmony Hub>
[2020-1-30 08:25:43] [homebridge-harmonyhub-plugin] {HarmonyHub} create new client for <Harmony Hub>
[2020-1-30 08:25:43] [eWeLink] eWeLink HTTPS API reports that there are a total of [4] devices registered
[2020-1-30 08:25:43] [eWeLink] Evaluating if devices need to be removed...
[2020-1-30 08:25:43] [eWeLink] Verifying that all cached devices are still registered with the API. Devices that are no longer registered with the API will be removed.
[2020-1-30 08:25:43] [eWeLink] Device [Garage Port], ID : [xxxxxxxxxxxxxxxxxxxxxx] is now splitted. It will be removed.
[2020-1-30 08:25:43] [eWeLink] Removing accessory [Garage Port]
[2020-1-30 08:25:43] [eWeLink] Device [Bio lampa], ID : [xxxxxxxxxxxxxxxxxxxxxxxxxxx] is now splitted. It will be removed.
[2020-1-30 08:25:43] [eWeLink] Removing accessory [Bio lampa]
[2020-1-30 08:25:43] [eWeLink] Device [Devas tak lampa], ID : [xxxxxxxxxxxxxxxxxxxxxx] is now splitted. It will be removed.
[2020-1-30 08:25:43] [eWeLink] Removing accessory [Devas tak lampa]
[2020-1-30 08:25:43] [eWeLink] Device [Kök lampa], ID : [xxxxxxxxxxxxxxxxxxxxxx] is now splitted. It will be removed.
[2020-1-30 08:25:43] [eWeLink] Removing accessory [Kök lampa]
[2020-1-30 08:25:43] [eWeLink] Evaluating if new devices need to be added...
[2020-1-30 08:25:43] [eWeLink] Device with ID [xxxxxxxxxxxxxxxxxxxxxx] is not configured. Add accessory.
[2020-1-30 08:25:43] [eWeLink] Device type for 1 is SOCKET
[2020-1-30 08:25:43] [eWeLink] Device [Garage Port], ID : [100057b4f4] will be added
[2020-1-30 08:25:43] [eWeLink] Found Accessory with Name : [Garage Port], Manufacturer : [DM-583], Status : [off], Is Online : [true], API Key: [xxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:43] [eWeLink] Device type for 1 is SOCKET
[2020-1-30 08:25:43] [eWeLink] Device type for 1 is SOCKET
[2020-1-30 08:25:43] [eWeLink] Device with ID [10008c950d] is not configured. Add accessory.
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device [Bio lampa], ID : [10008c950d] will be added
[2020-1-30 08:25:43] [eWeLink] Found Accessory with Name : [Bio lampa], Manufacturer : [TX1C], Status : [off], Is Online : [true], API Key: [xxxxxxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device with ID [xxxxxxxxxxxxxxxxxxxxxx] is not configured. Add accessory.
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device [Devas tak lampa], ID : [xxxxxxxxxxxxxxxxxxxxxx] will be added
[2020-1-30 08:25:43] [eWeLink] Found Accessory with Name : [Devas tak lampa], Manufacturer : [TX1C], Status : [off], Is Online : [true], API Key: [xxxxxxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device with ID [10008c93cc] is not configured. Add accessory.
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device [Kök lampa], ID : [10008c93cc] will be added
[2020-1-30 08:25:43] [eWeLink] Found Accessory with Name : [Kök lampa], Manufacturer : [TX1C], Status : [off], Is Online : [true], API Key: [xxxxxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] Device type for 6 is SWITCH
[2020-1-30 08:25:43] [eWeLink] API key retrieved from web service is [xxxxxxxxxxxxxxxxxxxxxx]
[2020-1-30 08:25:43] [eWeLink] Connecting to the WebSocket API at [wss://eu-pconnect4.coolkit.cc:8080/api/ws]
[TuyaDiscovery] UDP from ip adress 0x000055aa...0x0000aa55
[2020-1-30 08:25:44] [TuyaLan] Discovered Fönsterlampa kök (xxxxxxxxxxxxxxxxxxxxxx) identified as Outlet (3.3)
[TuyaAccessory] Changing ping gap for Fönsterlampa kök to 9s
[2020-1-30 08:25:44] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"158036914456300","apkVesrion":"1.8","os":"ios","at":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.  Xxxxxxxxxxxxxx","ts":"xxxxxxxxx","model":"iPhone10,6","romVersion":"11.1.2","sequence":xxxxxxxxxxxxxxxxx}]
[2020-1-30 08:25:44] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <2> activities: <Netflix, Tv>
[2020-1-30 08:25:44] [eWeLink] WebSocket messge received:  {"error":0,"apikey":"xxxxxxxxxxxxxxxxxxxxxxxxx","config":{"hb":1,"hbInterval":145},"sequence":"xxxxxxxxxxxxxxxxxxxxxx"}
[2020-1-30 08:25:44] [TuyaLan] Connected to Fönsterlampa kök
[TuyaAccessory] Sending first query to Fönsterlampa kök (3.3)
[TuyaAccessory] Fönsterlampa kök (3.3) didn't respond with its current state.
[2020-1-30 08:25:44] [TuyaLan] Ready to handle Fönsterlampa kök (Outlet:3.3) with signature {}
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[2020-1-30 08:25:44] [TuyaLan] Discovered Smart Socket (xxxxxxxxxxxxxxxxxxxxxx) identified as Outlet (3.3)
[TuyaAccessory] Changing ping gap for Smart Socket to 9s
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[2020-1-30 08:25:44] [TuyaLan] Discovered Fönsterlampa vardagsrum (xxxxxxxxxxxxxxxxxxxxxx) identified as Outlet (3.3)
[TuyaAccessory] Changing ping gap for Fönsterlampa vardagsrum to 9s
[2020-1-30 08:25:45] [TuyaLan] Connected to Fönsterlampa vardagsrum
[TuyaAccessory] Sending first query to Fönsterlampa vardagsrum (3.3)
[2020-1-30 08:25:45] [TuyaLan] Connected to Smart Socket
[TuyaAccessory] Sending first query to Smart Socket (3.3)
[TuyaAccessory] Fönsterlampa vardagsrum (3.3) didn't respond with its current state.
[2020-1-30 08:25:45] [TuyaLan] Ready to handle Fönsterlampa vardagsrum (Outlet:3.3) with signature {}
[TuyaAccessory] Smart Socket (3.3) didn't respond with its current state.
[2020-1-30 08:25:45] [TuyaLan] Ready to handle Smart Socket (Outlet:3.3) with signature {}
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[2020-1-30 08:25:45] [TuyaLan] Discovered Devas Fönsterlampa (xxxxxxxxxxxxxxxxxxxxxx) identified as Outlet (3.3)
[TuyaAccessory] Changing ping gap for Devas Fönsterlampa to 9s
[2020-1-30 08:25:45] [TuyaLan] Connected to Devas Fönsterlampa
[TuyaAccessory] Sending first query to Devas Fönsterlampa (3.3)
[TuyaAccessory] Devas Fönsterlampa (3.3) didn't respond with its current state.
[2020-1-30 08:25:45] [TuyaLan] Ready to handle Devas Fönsterlampa (Outlet:3.3) with signature {}
[2020-1-30 08:25:46] [Hue] Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
[2020-1-30 08:25:47] [Hue] Philips hue: 11 accessories
[2020-1-30 08:25:47] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Philips hue'...
[2020-1-30 08:25:47] [Hue] Philips hue: 2 services
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Golvlampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Oscar taklampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Spis Lampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Spis Lampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Tapplyse'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Biljardlampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Pannlampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Pannlampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Biljardlampa'...
[2020-1-30 08:25:47] [Hue] Initializing platform accessory 'Tvättlampa'...
Setup Payload:
X-HM://0023ISYWYMGED
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                             
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐
    │ 
    └────────────┘
                       
[2020-1-30 08:25:47] Homebridge is running on port 51826.
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[2020-1-30 08:25:54] [Homebridge Ui] Homebridge Config UI X v4.9.0 is listening on 0.0.0.0 port 8888
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from xxx.xxx.x.xx:xxxx 0x000055aa...0x0000aa55

And so on it goes throug

**Comment by iRayanKhan** [comment]
Clearing your cached accessories may help with the states being messed up, but I see you have a good number of accessories in this instance so I wouldn't want you to have to re orange what room certain accessories are in.

**Comment by Bogdis** [comment]
> Clearing your cached accessories may help with the states being messed up, but I see you have a good number of accessories in this instance so I wouldn't want you to have to re orange what room certain accessories are in.

Did that and didint help. :( Do you know why do i get the tuyadiscovery udp from all the time it scrolls thrugh all the ip:s and goes round and round again? My log gets very long
is there anything that you can se that its wrong?

Thank you.

**Comment by iRayanKhan** [comment]
Do you mind pasting your config file?

**Comment by Bogdis** [comment]
> Do you mind pasting your config file?

{
    "bridge": {
        "name": "HomeBridge",
        "username": "xxxxxxxxxxxxxxxxxxx",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "xxxxxxxxxxxxxxxxxxx",
            "host": "xxxxxxxxxxxxxxxxxxx",
            "filter": [
                {
                    "user": "xxxxxxxxxxxxxxxxxxx",
                    "player": "LG OLED65C9PLA"
                }
            ]
        },
        {
            "accessory": "Plex",
            "name": "Bio",
            "plex_token": "xxxxxxxxxxxxxxxxxxx",
            "host": "xxxxxxxxxxxxxxxxxxx",
            "filter": [
                {
                    "user": "xxxxxxxxxxxxxxxxxxx",
                    "player": "Bogdis-PC"
                }
            ]
        },
        {
            "accessory": "MagicHome",
            "name": "Oscars Säng Lampa",
            "ip": "xxxxxxxxxxxxxxxxxxx",
            "setup": "RGB"
        },
        {
            "accessory": "MagicHome",
            "name": "Devas Säng Lampa",
            "ip": "xxxxxxxxxxxxxxxxxxx",
            "setup": "RGB"
        },
        {
            "accessory": "DummySwitch",
            "name": "Switch 1"
        },
        {
            "accessory": "DummySwitch",
            "name": "Switch 2"
        }
    ],
    "platforms": [
        {
            "name": "Homebridge Ui",
            "port": 8888,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        },
        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "email": "xxxxxxxxxxxxxxxxxxx",
            "password": "xxxxxxxxxxxxxxxxxxx",
            "imei": "01234567-89AB-CDEF-0123-456789ABCDEF"
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        },
        {
            "name": "Hue",
            "users": {
                "xxxxxxxxxxxxxxxxxxx": "xxxxxxxxxxxxxxxxxxx"
            },
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "sensors": false,
            "platform": "Hue"
        },
        {
            "platform": "HarmonyHub",
            "name": "homebridge-harmonyhub-plugin"
        },
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Fönsterlampa kök",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "xxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxx"
                },
                {
                    "name": "Devas Fönsterlampa",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "xxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxx"
                },
                {
                    "name": "Fönsterlampa vardagsrum",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "xxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxx"
                },
                {
                    "name": "Smart Socket",
                    "type": "Outlet",
                    "manufacturer": "Teckin",
                    "model": "Wifi Mini Smart Life Outlet",
                    "id": "xxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxx"
                },
                {
                    "name": "Matlampa",
                    "type": "SimpleLight",
                    "manufacturer": "SavEnergy",
                    "model": "Smart Wifi Switch",
                    "id": "xxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxx"
                },
                {
                    "name": "Garage Port",
                    "type": "GarageDoor",
                    "manufacturer": "Wofea",
                    "model": "WiFi Switch Garage Door Controller",
                    "id": "xxxxxxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxxxxxxxx"
                }
            ]
        }
    ]
}

**Comment by iRayanKhan** [comment]
I wonder if defining the IP would work so it doesn't need to auto-discover.

**Comment by iRayanKhan** [comment]
Closing; installing issue resolved.
